; Seeed XIAO ESP32S3 — MNIST DS-CNN float32 (TFLM via esp-tflite-micro)
[env:xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = espidf
board_build.partitions = partitions.csv
monitor_speed = 115200
upload_speed = 460800
upload_flags =
	--before=usb-reset
	--after=hard_reset
monitor_filters = direct
