; ESP32-P4-Function-EV — MNIST CNN float32 (TFLM)
[platformio]
boards_dir = ../esp32-p4-function-ev/boards

[env:esp32_p4_ev]
platform = espressif32
board = esp32-p4-function-ev
framework = espidf
monitor_speed = 115200
upload_speed = 460800
board_build.partitions = partitions.csv
monitor_filters = direct
