#!/usr/bin/env python3
"""Emit tvm_io_bind.h with NETKIT_TVM_BIND_{INPUT,OUTPUT} macros from tvmgen_*.h."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


def _first_member(struct_body: str) -> str | None:
    m = re.search(r"(?:void|int8_t)\s*\*\s*([A-Za-z_][A-Za-z0-9_]*)\s*;", struct_body)
    return m.group(1) if m else None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--header", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--module", default="mnist_cnn_int8")
    args = ap.parse_args()

    text = args.header.read_text()
    mod = args.module
    in_re = re.compile(
        rf"struct\s+tvmgen_{re.escape(mod)}_inputs\s*\{{(.*?)\}}", re.S
    )
    out_re = re.compile(
        rf"struct\s+tvmgen_{re.escape(mod)}_outputs\s*\{{(.*?)\}}", re.S
    )
    in_m = in_re.search(text)
    out_m = out_re.search(text)
    if not in_m or not out_m:
        raise SystemExit(f"could not parse input/output structs in {args.header}")
    in_field = _first_member(in_m.group(1))
    out_field = _first_member(out_m.group(1))
    if not in_field or not out_field:
        raise SystemExit(f"missing pointer fields in {args.header}")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        f"""#pragma once
/* Generated by gen_tvm_io_bind.py — do not edit. */
#define NETKIT_TVM_BIND_INPUT(inputs, ptr)  do {{ (inputs).{in_field} = (ptr); }} while (0)
#define NETKIT_TVM_BIND_OUTPUT(outputs, ptr) do {{ (outputs).{out_field} = (ptr); }} while (0)
"""
    )
    print(f"input field:  {in_field}")
    print(f"output field: {out_field}")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
