#!/usr/bin/env python3
"""Emit embedded hand .nk blobs + first TCAS input for FVP bare-metal benchmarks."""

from __future__ import annotations

import argparse
from pathlib import Path

from netkit.reader import read_test_suite


def _emit_array(name: str, data: bytes) -> list[str]:
    lines = [f"alignas(8) const uint8_t {name}[] = {{"]
    for index, byte in enumerate(data):
        if index % 12 == 0:
            lines.append("    ")
        lines[-1] += f"0x{byte:02x}, "
    if lines[-1].endswith(", "):
        lines[-1] = lines[-1][:-2]
    lines.append("};")
    lines.append(f"const uint32_t {name}_size = {len(data)}u;")
    lines.append("")
    return lines


def _emit_float_array(name: str, values: list[float]) -> list[str]:
    joined = ", ".join(f"{value:.8f}f" for value in values)
    return [
        f"alignas(4) const float {name}[{len(values)}] = {{ {joined} }};",
        f"const uint32_t {name}_count = {len(values)}u;",
        "",
    ]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path("benchmarks/fvp/hand_fvp_embedded.c"),
    )
    args = parser.parse_args()

    models = {
        "mlp_hand_nk": "models/mlp_hand.nk",
        "cnn_hand_nk": "models/cnn_hand.nk",
    }

    lines = [
        "/* Auto-generated by tools/embed_hand_fvp_data.py — do not edit. */",
        "#include <stdint.h>",
        "",
    ]

    for symbol, path in models.items():
        blob = Path(path).read_bytes()
        suite = read_test_suite(path)
        if suite is None or not suite.cases:
            raise SystemExit(f"no TCAS cases in {path}")
        case = suite.cases[0]
        lines.extend(_emit_array(symbol, blob))
        lines.extend(_emit_float_array(f"{symbol}_input", list(case.input)))
        lines.append("")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
