# Map NETKIT_ARCH to CMSIS-DSP ARM_MATH_* preprocessor flags (see arm_math.h / CMSIS docs).
# Empty NETKIT_ARCH => native desktop / CPU build.

set(NETKIT_ARCH "" CACHE STRING
    "Target core (empty=desktop CPU): CM0, CM0PLUS, CM3, CM4, CM7, M23, M33, M55, M85, A32, NEON")

function(netkit_normalize_arch arch out_var)
    string(TOUPPER "${arch}" _arch)
    string(REGEX REPLACE "^CORTEX-" "" _arch "${_arch}")
    string(REGEX REPLACE "^CORTEX" "" _arch "${_arch}")
    set(${out_var} "${_arch}" PARENT_SCOPE)
endfunction()

function(netkit_resolve_architecture)
    set(_arm_math_defines "")
    set(_arm_math_neon OFF)
    set(_arm_math_loopunroll OFF)
    set(_arm_math_mve OFF)
    set(_cmsis_dsp OFF)
    set(_cmsis_nn OFF)
    set(_generic_nn OFF)
    set(_target_default cpu)

    if(NOT NETKIT_ARCH)
        message(STATUS "NETKIT_ARCH: (unset) — native desktop / CPU application")
        set(HOST ON CACHE BOOL "Enable CMSIS Host Mode" FORCE)

        set(_cmsis_dsp ON)
        set(_generic_nn ON)
        set(_arm_math_loopunroll ON)

        if(CMAKE_SYSTEM_PROCESSOR MATCHES "arm64" OR CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64")
            message(STATUS "Desktop CPU: Apple Silicon / Arm64 (portable CMSIS + optional NEON paths)")
            set(NEON ON CACHE BOOL "Enable NEON" FORCE)
        else()
            message(STATUS "Desktop CPU: x86_64 / Intel / AMD (portable C)")
            set(NEON OFF CACHE BOOL "Disable NEON" FORCE)
        endif()
    else()
        netkit_normalize_arch("${NETKIT_ARCH}" _arch)
        message(STATUS "NETKIT_ARCH: ${_arch} — embedded target")

        set(HOST OFF CACHE BOOL "Disable CMSIS Host Mode" FORCE)
        set(NEON OFF CACHE BOOL "Disable NEON for MCU" FORCE)
        set(_cmsis_dsp ON)
        set(_arm_math_loopunroll ON)

        if(_arch STREQUAL "CM0" OR _arch STREQUAL "M0")
            list(APPEND _arm_math_defines ARM_MATH_CM0)
            set(_target_default mcu)
            set(_cmsis_nn ON)
        elseif(_arch STREQUAL "CM0PLUS" OR _arch STREQUAL "M0PLUS" OR _arch STREQUAL "CM0+")
            list(APPEND _arm_math_defines ARM_MATH_CM0PLUS)
            set(_target_default mcu)
            set(_cmsis_nn ON)
        elseif(_arch STREQUAL "CM3" OR _arch STREQUAL "M3")
            list(APPEND _arm_math_defines ARM_MATH_CM3)
            set(_target_default mcu)
            set(_cmsis_nn ON)
        elseif(_arch STREQUAL "CM4" OR _arch STREQUAL "M4")
            list(APPEND _arm_math_defines ARM_MATH_CM4)
            set(_target_default mcu)
            set(_cmsis_nn ON)
        elseif(_arch STREQUAL "CM7" OR _arch STREQUAL "M7")
            list(APPEND _arm_math_defines ARM_MATH_CM7)
            set(_target_default mcu)
            set(_cmsis_nn ON)
        elseif(_arch STREQUAL "M23" OR _arch STREQUAL "CM23")
            list(APPEND _arm_math_defines ARM_MATH_ARMV8MBL)
            set(_target_default mcu)
            set(_cmsis_nn ON)
        elseif(_arch STREQUAL "M33" OR _arch STREQUAL "CM33")
            list(APPEND _arm_math_defines ARM_MATH_ARMV8MML)
            list(APPEND _arm_math_defines __DSP_PRESENT=1)
            set(_target_default mcu)
            set(_cmsis_nn ON)
        elseif(_arch STREQUAL "M55" OR _arch STREQUAL "CM55")
            list(APPEND _arm_math_defines ARM_MATH_M55)
            list(APPEND _arm_math_defines ARM_MATH_MVEF)
            list(APPEND _arm_math_defines ARM_MATH_MVEI)
            set(_arm_math_mve ON)
            set(_target_default mcu)
            set(_cmsis_nn ON)
        elseif(_arch STREQUAL "M85" OR _arch STREQUAL "CM85")
            list(APPEND _arm_math_defines ARM_MATH_M85)
            list(APPEND _arm_math_defines ARM_MATH_MVEF)
            list(APPEND _arm_math_defines ARM_MATH_MVEI)
            set(_arm_math_mve ON)
            set(_target_default mcu)
            set(_cmsis_nn ON)
        elseif(_arch STREQUAL "A32" OR _arch STREQUAL "CORTEXA32" OR _arch STREQUAL "MPU")
            list(APPEND _arm_math_defines ARM_MATH_A32)
            set(_target_default mpu)
            set(_generic_nn ON)
            set(NEON OFF CACHE BOOL "Disable NEON for A32 MPU" FORCE)
        elseif(_arch STREQUAL "NEON" OR _arch STREQUAL "CORTEXA" OR _arch STREQUAL "A64")
            list(APPEND _arm_math_defines ARM_MATH_NEON)
            set(_arm_math_neon ON)
            set(_target_default mpu)
            set(_generic_nn ON)
            set(NEON ON CACHE BOOL "Enable Hardware Neon" FORCE)
        else()
            message(FATAL_ERROR
                "Unknown NETKIT_ARCH '${NETKIT_ARCH}' (normalized '${_arch}'). "
                "Use CM0, CM0PLUS, CM3, CM4, CM7, M23, M33, M55, M85, A32, or NEON; leave unset for desktop.")
        endif()

        if(_target_default STREQUAL "mcu")
            set(CMSISCORE "${CMAKE_CURRENT_SOURCE_DIR}/third_party/CMSIS-Core/CMSIS/Core/Include" CACHE PATH "Path to CMSIS-Core" FORCE)
            message(STATUS "CMSIS-Core include: ${CMSISCORE}")
        endif()
    endif()

    set(NETKIT_ENV_ARM_MATH_DEFINES "${_arm_math_defines}" PARENT_SCOPE)
    set(NETKIT_ENV_ARM_MATH_NEON ${_arm_math_neon} PARENT_SCOPE)
    set(NETKIT_ENV_ARM_MATH_LOOPUNROLL ${_arm_math_loopunroll} PARENT_SCOPE)
    set(NETKIT_ENV_ARM_MATH_MVE ${_arm_math_mve} PARENT_SCOPE)
    set(NETKIT_ENV_CMSIS_DSP ${_cmsis_dsp} PARENT_SCOPE)
    set(NETKIT_ENV_CMSIS_NN ${_cmsis_nn} PARENT_SCOPE)
    set(NETKIT_ENV_GENERIC_NN ${_generic_nn} PARENT_SCOPE)
    set(_netkit_target_default ${_target_default} PARENT_SCOPE)
endfunction()
